version: "3.3"
services:

  mosquitto:
    image: eclipse-mosquitto:2.0.13
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - 1883:1883
    restart: "always"

  nodered:
    image: dynnodered:latest
    volumes:
      - ./nodered:/data
    ports:
      - 1880:1880
    restart: "always"

  influxdb:
    image: influxdb:2.1-alpine
    volumes:
      - ./influxdb/data:/var/lib/influxdb2
    ports:
      - 8086:8086
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=nodered
      - DOCKER_INFLUXDB_INIT_PASSWORD=nodered8086
      - DOCKER_INFLUXDB_INIT_ORG=nodered
      - DOCKER_INFLUXDB_INIT_BUCKET=nodered
      - DOCKER_INFLUXDB_INIT_RETENTION=24h
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=kasvit-kasvaa-vain
    restart: "always"

  grafana:
    image: grafana/grafana:8.2.3
    ports:
      - 3000:3000
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/dashboards
    user: "${UID}:${GID}"
    restart: "always"
