version: "3.3"
services:
  mosquitto:
    image: eclipse-mosquitto:2.0.13
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - 1883:1883
  nodered:
    image: nodered/node-red:2.1.3
    volumes:
      - ./nodered:/data
    ports:
      - 1880:1880
