{
 "title": "Dynamic Charge Monitor",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Charging Current",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "query": "from(bucket: \"dynloadmgr\") \n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)  \n  |> filter(fn: (r) => r._measurement == \"chargeCurrent\" and r._field == \"current\")\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field: \"Charging Current\"}))"
    },
    {
     "query": "import \"math\"\nfrom(bucket: \"dynloadmgr\") \n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)  \n  |> filter(fn: (r) => r._measurement == \"phaseCurrents\" and (r._field == \"l1\" or r._field == \"l2\" or r._field == \"l3\"))\n  |> pivot(rowKey:[\"_time\"],columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({ r with \"Max Phase\": math.mMax(x: math.mMax(x: r.l1, y: r.l2),y: r.l3) }))\n  |> drop(columns: [\"l1\", \"l2\", \"l3\", \"_start\", \"_stop\", \"_measurement\"])"
    }
   ]
  },
  {
   "title": "Charging Status",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dynloadmgr\") \n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)  \n  |> filter(fn: (r) => r._measurement == \"chargeCurrent\" and r._field == \"status\")\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field: \"Charging Status\"}))"
    }
   ]
  },
  {
   "title": "Charging Current",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dynloadmgr\") \n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)  \n  |> filter(fn: (r) => r._measurement == \"chargeCurrent\" and r._field == \"current\")\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field: \"Charging Current\"}))"
    },
    {
     "query": "import \"math\"\nfrom(bucket: \"dynloadmgr\") \n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)  \n  |> filter(fn: (r) => r._measurement == \"phaseCurrents\" and (r._field == \"l1\" or r._field == \"l2\" or r._field == \"l3\"))\n  |> pivot(rowKey:[\"_time\"],columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({ r with \"Max Phase\": math.mMax(x: math.mMax(x: r.l1, y: r.l2),y: r.l3) }))\n  |> drop(columns: [\"l1\", \"l2\", \"l3\", \"_start\", \"_stop\", \"_measurement\"])"
    },
    {
     "query": "from(bucket: v.defaultBucket) \n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)  \n  |> filter(fn: (r) => r._measurement == \"chargeCurrent\" and r._field == \"status\")\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field: \"Charging Status\"}))"
    },
    {
     "query": "from(bucket: v.defaultBucket) \n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)  \n  |> filter(fn: (r) => r._measurement == \"chargeCurrent\" and r._field == \"maxCurrent\")\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field: \"Current Limit\"}))"
    }
   ]
  },
  {
   "title": "Phase Currents",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "query": "from(bucket: \"dynloadmgr\") \n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)  \n  |> filter(fn: (r) => r._measurement == \"phaseCurrents\" and r._field == \"l1\")\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field: \"L1\"}))"
    },
    {
     "query": "from(bucket: \"dynloadmgr\") \n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)  \n  |> filter(fn: (r) => r._measurement == \"phaseCurrents\" and r._field == \"l2\")\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field: \"L2\"}))"
    },
    {
     "query": "from(bucket: v.defaultBucket) \n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)  \n  |> filter(fn: (r) => r._measurement == \"phaseCurrents\" and r._field == \"l3\")\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field: \"L3\"}))"
    }
   ]
  },
  {
   "title": "Phase Currents",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dynloadmgr\") \n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)  \n  |> filter(fn: (r) => r._measurement == \"phaseCurrents\" and r._field == \"l1\")\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field: \"L1\"}))"
    },
    {
     "query": "from(bucket: \"dynloadmgr\") \n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)  \n  |> filter(fn: (r) => r._measurement == \"phaseCurrents\" and r._field == \"l2\")\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field: \"L2\"}))"
    },
    {
     "query": "from(bucket: \"dynloadmgr\") \n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)  \n  |> filter(fn: (r) => r._measurement == \"phaseCurrents\" and r._field == \"l3\")\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field: \"L3\"}))"
    }
   ]
  }
 ]
}