{
 "title": "Dynamic Charge Monitor",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Charge Current",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket) \n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)  \n  |> filter(fn: (r) => r._measurement == \"chargeCurrent\")\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field: \"Charging current\"}))"
    },
    {
     "query": "import \"math\"\nfrom(bucket: v.defaultBucket) \n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)  \n  |> filter(fn: (r) => r._measurement == \"phaseCurrents\" and (r._field == \"l1\" or r._field == \"l2\" or r._field == \"l3\"))\n  |> pivot(rowKey:[\"_time\"],columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({ r with \"Max phase\": math.mMax(x: math.mMax(x: r.l1, y: r.l2),y: r.l3) }))\n  |> drop(columns: [\"l1\", \"l2\", \"l3\", \"_start\", \"_stop\", \"_measurement\"])"
    }
   ]
  },
  {
   "title": "Charge Current",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket) \n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)  \n  |> filter(fn: (r) => r._measurement == \"chargeCurrent\")\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field: \"Charging current\"}))"
    }
   ]
  },
  {
   "title": "Phase Currents",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 17, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket) \n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)  \n  |> filter(fn: (r) => r._measurement == \"phaseCurrents\" and r._field == \"l1\")\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field: \"L1\"}))"
    },
    {
     "query": "from(bucket: v.defaultBucket) \n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)  \n  |> filter(fn: (r) => r._measurement == \"phaseCurrents\" and r._field == \"l2\")\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field: \"L2\"}))"
    },
    {
     "query": "from(bucket: v.defaultBucket) \n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)  \n  |> filter(fn: (r) => r._measurement == \"phaseCurrents\" and r._field == \"l3\")\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field: \"L3\"}))"
    }
   ]
  },
  {
   "title": "Charge Power",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "toKws = (curr) => 3.0 * ((curr * 230.0) / 1000.0)\n\nfrom(bucket: v.defaultBucket) \n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)  \n  |> filter(fn: (r) => r._measurement == \"chargeCurrent\")\n  |> map(fn: (r) => ({_value: toKws(curr: r._value), _time:r._time, _field: \"Charging current\"}))"
    }
   ]
  }
 ]
}