{
 "title": "Today",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Energy",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"homeenergy\") \n  |> range(start: today())  \n  |> filter(fn: (r) => r._measurement == \"houseConsumption\" and r._field == \"consumption\")\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field: \"Prize\"}))\n  |> sum()"
    }
   ]
  },
  {
   "title": "Cost",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "query": "from(bucket: \"homeenergy\") \n  |> range(start: today())  \n  |> filter(fn: (r) => r._measurement == \"houseConsumption\" and r._field == \"prize\")\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field: \"Prize\"}))\n  |> sum()"
    }
   ]
  },
  {
   "title": "Current Prize",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"homeenergy\") \n  |> range(start: today())  \n  |> filter(fn: (r) => r._measurement == \"houseConsumption\" and r._field == \"hourPrize\")\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field: \"Hour Prize\"}))"
    }
   ]
  },
  {
   "title": "Hour Prize and Consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "from(bucket: \"homeenergy\") \n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop) \n  |> filter(fn: (r) => r._measurement == \"houseConsumption\")\n  |> filter(fn: (r) => r._field == \"consumption\")\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field: \"Energy\"}))\n  |> aggregateWindow(every: 1h, fn: sum)\n  \n"
    },
    {
     "query": "from(bucket: \"homeenergy\") \n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop) \n  |> filter(fn: (r) => r._measurement == \"houseConsumption\")\n  |> filter(fn: (r) => r._field == \"prize\")\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field: \"Prize\"}))\n  |> aggregateWindow(every: 1h, fn: sum)\n"
    }
   ]
  },
  {
   "title": "Prize vs. Consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "from(bucket: \"homeenergy\") \n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop) \n  |> filter(fn: (r) => r._measurement == \"houseConsumption\")\n  |> filter(fn: (r) => r._field == \"consumption\")\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field: \"Energy\"}))\n   |> aggregateWindow(every: 1h, fn: sum)\n"
    },
    {
     "query": "from(bucket: \"homeenergy\") \n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop) \n  |> filter(fn: (r) => r._measurement == \"houseConsumption\")\n  |> filter(fn: (r) => r._field == \"hourPrize\")\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field: \"Instantaneous Prize\"}))\n  |> aggregateWindow(every: 1h, fn: mean)\n"
    }
   ]
  }
 ]
}